# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mlc-notes',
                'doc_host': 'https://vguerra.github.io',
                'git_url': 'https://github.com/vguerra/mlc-notes',
                'lib_path': 'mlc_notes'},
  'syms': {'mlc_notes.core': {'mlc_notes.core.foo': ('core.html#foo', 'mlc_notes/core.py')}}}
